config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :notes
  resources :collections do
    resources :decks
  end

  root 'collections#index'

  # scope '(:locale)',
  #     locale: Regexp.new(I18n.available_locales.map(&:to_s).join('|')) do

  
    #root 'users#index'
  # end
end

app/models/collection.rb
# == Schema Information
#
# Table name: col
#
#  id     :integer          primary key
#  crt    :integer          not null
#  mod    :integer          not null
#  scm    :integer          not null
#  ver    :integer          not null
#  dty    :integer          not null
#  usn    :integer          not null
#  ls     :integer          not null
#  conf   :text             not null
#  models :text             not null
#  decks  :text             not null
#  dconf  :text             not null
#  tags   :text             not null
#

# Model Collection defines the Collection
#
class Collection < ApplicationRecord

  establish_connection ActiveRecord::Base.configurations["anki"] if Rails.env.development?
  self.table_name = "col"

  validates :crt, :mod, :scm, :ver, :dty, :usn, :ls, :conf, :models, :dconf, :tags,
      presence: true

  serialize :conf, JSON
  serialize :models, JSON
  serialize :decks, JSON
  serialize :dconf, JSON
  serialize :tags, JSON

  scope :ordered, -> { order(:crt) }

  def decks
    return unless attributes['decks']
    @decks_hash ||= attributes['decks'].each_with_object({}) do |(id, attrs), result|
      deck = Deck.new attrs
      deck.id = id
      deck.collection = self
      result[id] = deck
    end
  end

  def models
    return unless attributes['models']
    @models_hash ||= attributes['models'].each_with_object({}) do |(id, attrs), result|
      model = Model.new attrs
      model.id = id.to_i
      model.collection = self
      result[id] = model
    end
  end

  def reload
    @decks_hash = nil
    @models_hash = nil
    super
  end

  def save_deck(deck)
    add_or_replace_deck deck
    save
  end

  def save_deck!(deck)
    add_or_replace_deck deck
    save!
  end

  private

  def add_or_replace_deck(deck)
    @decks_hash = nil
    attributes['decks'][deck.id.to_s] = deck.to_hash
  end

end

app/controllers/collections_controller.rb
# This is the main controller to process model Collection
#
class CollectionsController < ApplicationController

  before_action :set_collection, only: [:show, :edit, :update, :destroy]

  # GET /collections
  def index
    @collections = Collection.all
    respond_to do |format|
      format.html do
        @grid = initialize_grid @collections
      end
      format.json do
        @collections = @collections.page(params[:page]) if params[:page].present?
        @collections = @collections.per(params[:per_page]) if params[:per_page].present?
      end
    end
  end

  # GET /collections/1
  def show
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to @collection, notice: t('collections.was_created') }
        format.json { render :show, status: :created, location: @collection }
      else
        logger.info "CollectionsController@#{__LINE__}#create #{@collection.errors.messages}"
        format.html { render :new }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to @collection, notice: t('collections.was_updated') }
        format.json { render :show, status: :ok, location: @collection }
      else
        logger.info "CollectionsController@#{__LINE__}#update #{@collection.errors.messages}"
        format.html { render :edit }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /collections/1
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url, notice: t('collections.was_deleted') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_collection
    @collection = Collection.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def collection_params
    list = %i[
      crt mod scm ver dty usn ls tags
    ]
    list << {conf: {}, dconf: {}, decks: {}, models: {}}
    params.require(:collection).permit(*list)
  end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.haml
= form_for(collection) do |f|
  - if collection.errors.any?
    #error_explanation
      %h2
        = t 'errors.template.header', model: t('.collection'), count: collection.errors.count
      %ul
        - collection.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :crt
    %br
    = f.number_field :crt
  .field
    = f.label :mod
    %br
    = f.number_field :mod
  .field
    = f.label :scm
    %br
    = f.number_field :scm
  .field
    = f.label :ver
    %br
    = f.number_field :ver
  .field
    = f.label :dty
    %br
    = f.number_field :dty
  .field
    = f.label :usn
    %br
    = f.number_field :usn
  .field
    = f.label :ls
    %br
    = f.number_field :ls
  .field
    = f.label :conf
    %br
    = f.text_area :conf
  .field
    = f.label :models
    %br
    = f.text_area :models
  -# .field
    = f.label :decks
    %br
    = f.text_area :decks
  .field
    = f.label :dconf
    %br
    = f.text_area :dconf
  .field
    = f.label :tags
    %br
    = f.text_area :tags

  .actions
    = f.submit

app/views/collections/edit.html.haml
- title t('.title')

%p.nav
  - if can? :index, Collection
    = link_to t('back'), collections_path, class: 'index'
  - if can? :show, @collection
    = link_to t('show'), @collection, class: 'show'

= render 'form', collection: @collection

app/views/collections/index.html.haml
- title t('.title')

- if can? :new, Collection
  %p.nav= link_to t('.new_collection'), new_collection_path, class: 'new'

- if @collections.limit(1).size > 0
  - if @grid
    = grid @grid do |g|
      - g.column name: Collection.human_attribute_name(:crt),
        attribute: 'crt' do |collection|
        - Time.at collection.crt
      - g.column name: Collection.human_attribute_name(:mod),
        attribute: 'mod' do |collection|
        - Time.at collection.mod / 1000
      - g.column name: Collection.human_attribute_name(:scm),
        attribute: 'scm' do |collection|
        - Time.at collection.scm / 1000
      - g.column name: Collection.human_attribute_name(:ls),
        attribute: 'ls' do |collection|
        - Time.at collection.ls / 1000
      - g.column name: Collection.human_attribute_name(:ver),
        attribute: 'ver' do |collection|
        - collection.ver
      - g.column name: Collection.human_attribute_name(:dty),
        attribute: 'dty' do |collection|
        - collection.dty
      - g.column name: Collection.human_attribute_name(:usn),
        attribute: 'usn' do |collection|
        - collection.usn
      -# g.column name: Collection.human_attribute_name(:conf),
        attribute: 'conf' do |collection|
        - collection.conf
      -# g.column name: Collection.human_attribute_name(:models),
        attribute: 'models' do |collection|
        - collection.models
      -# g.column name: Collection.human_attribute_name(:decks),
        attribute: 'decks' do |collection|
        - collection.decks
      -# g.column name: Collection.human_attribute_name(:dconf),
        attribute: 'dconf' do |collection|
        - collection.dconf
      -# g.column name: Collection.human_attribute_name(:tags),
        attribute: 'tags' do |collection|
        - collection.tags
      - g.column do |collection|
        - if can? :show, collection
          - link_to t('show'), collection, class: 'show'
      - g.column do |collection|
        - if can? :edit, collection
          - link_to t('edit'), edit_collection_path(collection), class: 'edit'
      - g.column do |collection|
        - if can? :destroy, collection
          - link_to t('destroy'), collection,
            data: {confirm: t('.confirm', default: 'Are you sure?')},
            method: :delete, class: 'destroy'
      - g.column do |collection|
        - if can? :index_decks, collection
          - link_to t('.decks'), collection_decks_path(collection_id: collection.id),
              class: 'index'
  -else
    %table
      %thead
        %tr
          %th= Collection.human_attribute_name :crt
          %th= Collection.human_attribute_name :mod
          %th= Collection.human_attribute_name :scm
          %th= Collection.human_attribute_name :ls
          %th= Collection.human_attribute_name :ver
          %th= Collection.human_attribute_name :dty
          %th= Collection.human_attribute_name :usn
          -#%th= Collection.human_attribute_name :conf
          -#%th= Collection.human_attribute_name :models
          -#%th= Collection.human_attribute_name :decks
          -#%th= Collection.human_attribute_name :dconf
          -#%th= Collection.human_attribute_name :tags
          %th{colspan: 3}= t 'actions'

      %tbody
        - @collections.each do |collection|
          %tr{class: cycle(:odd, :even)}
            %td= Time.at collection.crt
            %td= Time.at collection.mod / 1000
            %td= Time.at collection.scm / 1000
            %td= Time.at collection.ls / 1000
            %td= collection.ver
            %td= collection.dty
            %td= collection.usn
            -#%td= collection.conf
            -#%td= collection.models
            -#%td= collection.decks
            -#%td= collection.dconf
            -#%td= collection.tags
            %td.action
              - if can? :show, collection
                = link_to t('show'), collection, class: 'show'
            %td.action
              - if can? :edit, collection
                = link_to t('edit'), edit_collection_path(collection), class: 'edit'
            %td.action
              - if can? :destroy, collection
                = link_to t('destroy'), collection,
                  data: {confirm: t('.confirm', default: 'Are you sure?')},
                  method: :delete, class: 'destroy'
- else
  .empty
    = t '.empty'

app/views/collections/new.html.haml
- title t('.title')

- if can? :index, Collection
  %p.nav= link_to t('back'), collections_path, class: 'index'

= render 'form', collection: @collection

app/views/collections/show.html.haml
- title t('.title')

%p.nav
  - if can? :index, Collection
    = link_to t('back'), collections_path, class: 'index'
  - if can? :edit, @collection
    = link_to t('edit'), edit_collection_path(@collection), class: 'edit'

%dl
  %dt= Collection.human_attribute_name :crt
  %dd= Time.at @collection.crt
  %dt= Collection.human_attribute_name :mod
  %dd= Time.at @collection.mod / 1000
  %dt= Collection.human_attribute_name :scm
  %dd= Time.at @collection.scm / 1000
  %dt= Collection.human_attribute_name :ls
  %dd= Time.at @collection.ls / 1000
  %dt= Collection.human_attribute_name :ver
  %dd= @collection.ver
  %dt= Collection.human_attribute_name :dty
  %dd= @collection.dty
  %dt= Collection.human_attribute_name :usn
  %dd= @collection.usn
  %dt= Collection.human_attribute_name :conf
  %dd
    %dl
      - @collection.conf.each do |key, value|
        %dt{class: key}=key
        %dd{class: key}=value.inspect
  %dt= Collection.human_attribute_name :dconf
  %dd
    %dl
      - @collection.dconf.each do |key, value|
        %dt{class: key}=key
        %dd
          - value.each do |k, v|
            %dt{class: "#{key}-#{k}"}= k
            %dd{class: "#{key}-#{k}"}
              - if k == "mod"
                = v
                = ' = '
                = Time.at v
              - else
                = v.inspect
  %dt= Collection.human_attribute_name :models
  %dd
    %dl
      - @collection.models.each do |key, value|
        %dt{class: key}
          = key
          = ' = '
          = Time.at key.to_i / 1000
        %dd{class: "#{key}-name"}= value.name
        %dd
          %dl
            - Array(value.flds).each do |field|
              %dd= field['name']
        -#%dd{class: key}=value.inspect
  %dt= Collection.human_attribute_name :decks
  %dd
    %dl
      - @collection.decks.each do |id, deck|
        %dt{class: deck.id}
          = Time.at deck.id.to_i / 1000
        %dd{class: "#{deck.id}-name"}
          = deck.name
          ***
          = Time.at deck.id.to_i / 1000
  %dt= Collection.human_attribute_name :tags
  %dd= @collection.tags