config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :notes
  resources :collections do
    resources :decks
  end

  root 'collections#index'

  # scope '(:locale)',
  #     locale: Regexp.new(I18n.available_locales.map(&:to_s).join('|')) do

  
    #root 'users#index'
  # end
end

app/models/note.rb
# == Schema Information
#
# Table name: notes
#
#  id    :integer          primary key
#  guid  :text             not null
#  mid   :integer          not null
#  mod   :integer          not null
#  usn   :integer          not null
#  tags  :text             not null
#  flds  :text             not null
#  sfld  :integer          not null
#  csum  :integer          not null
#  flags :integer          not null
#  data  :text             not null
#

# Model Note defines notes
#
class Note < ApplicationRecord

  TABLE91 = ('0'..'9').to_a + ('a'..'z').to_a + ('A'..'Z').to_a +
      "!#$%&()*+,-./:;<=>?@[]^_`{|}~".split('')
  TABLE91_SIZE = TABLE91.size

  establish_connection ActiveRecord::Base.configurations["anki"] if Rails.env.development?

  has_many :cards, foreign_key: :nid

  before_validation :generate_guid
  validates :mid, :mod, :usn, :flds, :sfld, :csum, :flags,
      presence: true

  scope :ordered, -> { order(:id) }
  scope :for_deck, -> (deck) do
    deck = deck.id if deck.is_a? Deck
    joins(:cards).where(cards: {did: deck}).distinct
  end
  scope :for_model, -> (model) do
    model = model.id if model.is_a? Model
    where mid: model
  end

  def fields
    @fieflds ||= flds.split("\x1f").each_with_index.each_with_object({}) do |(field, index), result|
      result[model.flds[index]['name']] = field
    end
  end

  def model
    return @model if @model
    Collection.all.detect do |collecion|
      @model = collecion.models[mid.to_s]
    end
    @model
  end

  def model=(model)
    @model = model if model.is_a? Model
  end

  def method_missing(method, *args)
    return super if args.size != 0
    key = method.to_s.camelcase
    return super unless fields.keys.include? key
    fields[key]
  end

  private

  def generate_guid
    while guid.blank? or Note.where(guid: guid).count > 1
      self.guid = guid64
    end
  end

  def guid64
    start = rand(0...2**64)
    res = ""
    while start > 0
      res << TABLE91[start % TABLE91_SIZE]
      start /= TABLE91_SIZE
    end
    res
  end
end

app/controllers/notes_controller.rb
# This is the main controller to process model Note
#
class NotesController < ApplicationController

  load_and_authorize_resource

  # GET /notes
  def index
    respond_to do |format|
      format.html do
        @grid = initialize_grid @notes
      end
      format.json do
        @notes = @notes.page(params[:page]) if params[:page].present?
        @notes = @notes.per(params[:per_page]) if params[:per_page].present?
      end
    end
  end

  # GET /notes/1
  def show
  end

  # GET /notes/new
  def new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  def create
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: t('notes.was_created') }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: t('notes.was_updated') }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: t('notes.was_deleted') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # def set_note
  #   @note = Note.find(params[:id])
  # end

  # Never trust parameters from the scary internet, only allow the white list through.
  def note_params
    list = [
      :mid, :mod, :usn, :tags, :flds, :sfld, :csum, :flags, :data
    ]
    params.require(:note).permit(*list)
  end
end

app/views/notes/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@note) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :mid
    = f.input :mod
    = f.input :usn
    = f.input :tags
    = f.input :flds
    = f.input :sfld
    = f.input :csum
    = f.input :flags
    = f.input :data

  .form-actions
    = f.button :submit

app/views/notes/edit.html.haml
- title t('.title')

%p.nav
  - if can? :index, Note
    = link_to t('back'), notes_path, class: 'index'
  - if can? :show, @note
    = link_to t('show'), @note, class: 'show'

= render 'form', note: @note

app/views/notes/index.html.haml
- title t('.title')

- if can? :new, Note
  %p.nav= link_to t('.new_note'), new_note_path, class: 'new'

- if @notes.limit(1).size > 0
  - if @grid
    = grid @grid do |g|
      -# g.column name: Note.human_attribute_name(:guid),
        class: 'guid', attribute: 'guid' do |note|
        - note.guid
      - g.column name: Note.human_attribute_name(:mid),
        class: 'mid', attribute: 'mid',
        custom_filter: :auto do |note|
        - note.mid
      - g.column name: Note.human_attribute_name(:model_name),
        class: 'model_name', attribute: 'mid' do |note|
        - note.model.name
      - g.column name: Note.human_attribute_name(:mod),
        class: 'mod', attribute: 'mod' do |note|
        - Time.at note.mod
      - g.column name: Note.human_attribute_name(:usn),
        class: 'usn numeric', attribute: 'usn' do |note|
        - note.usn
      - g.column name: Note.human_attribute_name(:tags),
        class: 'tags', attribute: 'tags' do |note|
        - note.tags
      -# g.column name: Note.human_attribute_name(:flds),
        class: 'flds', attribute: 'flds' do |note|
        - note.flds
      -# g.column name: Note.human_attribute_name(:sfld),
        class: 'sfld', attribute: 'sfld' do |note|
        - note.sfld
      - g.column name: Note.human_attribute_name(:csum),
        class: 'csum numeric', attribute: 'csum' do |note|
        - note.csum
      - g.column name: Note.human_attribute_name(:flags),
        class: 'flags numeric', attribute: 'flags' do |note|
        - note.flags
      -# g.column name: Note.human_attribute_name(:data),
        class: 'data', attribute: 'data' do |note|
        - note.data
      - g.column do |note|
        - if can? :show, note
          - link_to t('show'), note, class: 'show'
      - g.column do |note|
        - if can? :edit, note
          - link_to t('edit'), edit_note_path(note), class: 'edit'
      - g.column do |note|
        - if can? :destroy, note
          - link_to t('destroy'), note,
            data: {confirm: t('.confirm', default: 'Are you sure?')},
            method: :delete, class: 'destroy'
  -else
    %table
      %thead
        %tr
          -# %th= Note.human_attribute_name :guid
          %th= Note.human_attribute_name :mid
          %th= Note.human_attribute_name :mod
          %th= Note.human_attribute_name :usn
          %th= Note.human_attribute_name :tags
          -# %th= Note.human_attribute_name :flds
          -# %th= Note.human_attribute_name :sfld
          %th= Note.human_attribute_name :csum
          %th= Note.human_attribute_name :flags
          -# %th= Note.human_attribute_name :data
          %th{colspan: 3}= t 'actions'

      %tbody
        - @notes.each do |note|
          %tr{class: cycle(:odd, :even)}
            -# %td.guid= note.guid
            %td.mid= note.mid
            %td.mod= Time.at note.mod
            %td.usn= note.usn
            %td.tags= note.tags
            -# %td.flds= note.flds
            -# %td.sfld= note.sfld
            %td.csum= note.csum
            %td.flags= note.flags
            -# %td.data= note.data
            %td.action
              - if can? :show, note
                = link_to t('show'), note, class: 'show'
            %td.action
              - if can? :edit, note
                = link_to t('edit'), edit_note_path(note), class: 'edit'
            %td.action
              - if can? :destroy, note
                = link_to t('destroy'), note,
                  data: {confirm: t('.confirm', default: 'Are you sure?')},
                  method: :delete, class: 'destroy'
- else
  .empty
    = t '.empty'

app/views/notes/new.html.haml
- title t('.title')

- if can? :index, Note
  %p.nav= link_to t('back'), notes_path, class: 'index'

= render 'form', note: @note

app/views/notes/show.html.haml
- title t('.title')

%p.nav
  - if can? :index, Note
    = link_to t('back'), notes_path, class: 'index'
  - if can? :edit, @note
    = link_to t('edit'), edit_note_path(@note), class: 'edit'

%dl
  %dt= Note.human_attribute_name :guid
  %dd.guid= @note.guid
  %dt= Note.human_attribute_name :mid
  %dd.mid= @note.mid
  %dt= Note.human_attribute_name :model_name
  %dd.model_name= @note.model.name
  %dt= Note.human_attribute_name :mod
  %dd.mod= Time.at @note.mod
  %dt= Note.human_attribute_name :usn
  %dd.usn= @note.usn
  %dt= Note.human_attribute_name :tags
  %dd.tags= @note.tags.inspect
  %dt= Note.human_attribute_name :fields
  %dd.fields
    %dl
      - @note.fields.each do |name, field|
        %dt
          = name
        %dd.field
          = field
  -# %dt= Note.human_attribute_name :sfld
  -# %dd.sfld= @note.sfld
  %dt= Note.human_attribute_name :csum
  %dd.csum= @note.csum
  %dt= Note.human_attribute_name :flags
  %dd.flags= @note.flags
  %dt= Note.human_attribute_name :data
  %dd.data= @note.data