config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :notes
  resources :collections do
    resources :decks
  end

  root 'collections#index'

  # scope '(:locale)',
  #     locale: Regexp.new(I18n.available_locales.map(&:to_s).join('|')) do

  
    #root 'users#index'
  # end
end

app/models/card.rb
# == Schema Information
#
# Table name: cards
#
#  id         :integer          not null, primary key
#  nid        :integer
#  did        :integer
#  ord        :integer
#  mod        :integer
#  usn        :integer
#  type       :integer
#  queue      :integer
#  due        :integer
#  ivl        :integer
#  factor     :integer
#  reps       :integer
#  lapses     :integer
#  left       :integer
#  odue       :integer
#  odid       :integer
#  flags      :integer
#  data       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

# Model Card defines Cards of the Node
#
class Card < ApplicationRecord

  establish_connection ActiveRecord::Base.configurations["anki"] if Rails.env.development?
  self.inheritance_column = nil

  belongs_to :note, foreign_key: :nid

  validates :nid, :did, :ord, :mod, :usn, :type, :queue, :due, :ivl,
          :factor, :reps, :lapses, :left, :odue, :odid, :flags,
      presence: true

  scope :ordered, -> { order(:nid) }

end

app/controllers/cards_controller.rb
# This is the main controller to process model Card
#
class CardsController < ApplicationController

  load_and_authorize_resource

  # GET /cards
  def index
    respond_to do |format|
      format.html do
        @grid = initialize_grid @cards
      end
      format.json do
        @cards = @cards.page(params[:page]) if params[:page].present?
        @cards = @cards.per(params[:per_page]) if params[:per_page].present?
      end
    end
  end

  # GET /cards/1
  def show
  end

  # GET /cards/new
  def new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  def create
    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: t('cards.was_created') }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: t('cards.was_updated') }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: t('cards.was_deleted') }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  # def set_card
  #   @card = Card.find(params[:id])
  # end

  # Never trust parameters from the scary internet, only allow the white list through.
  def card_params
    list = [
      :nid, :did, :ord, :mod, :usn, :type, :queue, :due, :ivl, :factor, :reps, :lapses, :left, :odue, :odid, :flags, :data
    ]
    params.require(:card).permit(*list)
  end
end

app/views/cards/_form.html.haml
-# frozen_string_literal: true
= simple_form_for(@card) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :nid
    = f.input :did
    = f.input :ord
    = f.input :mod
    = f.input :usn
    = f.input :type
    = f.input :queue
    = f.input :due
    = f.input :ivl
    = f.input :factor
    = f.input :reps
    = f.input :lapses
    = f.input :left
    = f.input :odue
    = f.input :odid
    = f.input :flags
    = f.input :data

  .form-actions
    = f.button :submit

app/views/cards/edit.html.haml
- title t('.title')

%p.nav
  - if can? :index, Card
    = link_to t('back'), cards_path, class: 'index'
  - if can? :show, @card
    = link_to t('show'), @card, class: 'show'

= render 'form', card: @card

app/views/cards/index.html.haml
- title t('.title')

- if can? :new, Card
  %p.nav= link_to t('.new_card'), new_card_path, class: 'new'

- if @cards.limit(1).size > 0
  - if @grid
    = grid @grid do |g|
      - g.column name: Card.human_attribute_name(:nid),
        class: 'nid', attribute: 'nid' do |card|
        - card.nid
      - g.column name: Card.human_attribute_name(:did),
        class: 'did', attribute: 'did' do |card|
        - card.did
      - g.column name: Card.human_attribute_name(:ord),
        class: 'ord numeric', attribute: 'ord' do |card|
        - card.ord
      - g.column name: Card.human_attribute_name(:mod),
        class: 'mod', attribute: 'mod' do |card|
        - card.mod
      - g.column name: Card.human_attribute_name(:usn),
        class: 'usn numeric', attribute: 'usn' do |card|
        - card.usn
      - g.column name: Card.human_attribute_name(:type),
        class: 'type numeric', attribute: 'type' do |card|
        - card.type
      - g.column name: Card.human_attribute_name(:queue),
        class: 'queue numeric', attribute: 'queue' do |card|
        - card.queue
      - g.column name: Card.human_attribute_name(:due),
        class: 'due numeric', attribute: 'due' do |card|
        - card.due
      - g.column name: Card.human_attribute_name(:ivl),
        class: 'ivl numeric', attribute: 'ivl' do |card|
        - card.ivl
      - g.column name: Card.human_attribute_name(:factor),
        class: 'factor numeric', attribute: 'factor' do |card|
        - card.factor
      - g.column name: Card.human_attribute_name(:reps),
        class: 'reps numeric', attribute: 'reps' do |card|
        - card.reps
      - g.column name: Card.human_attribute_name(:lapses),
        class: 'lapses numeric', attribute: 'lapses' do |card|
        - card.lapses
      - g.column name: Card.human_attribute_name(:left),
        class: 'left numeric', attribute: 'left' do |card|
        - card.left
      - g.column name: Card.human_attribute_name(:odue),
        class: 'odue numeric', attribute: 'odue' do |card|
        - card.odue
      - g.column name: Card.human_attribute_name(:odid),
        class: 'odid numeric', attribute: 'odid' do |card|
        - card.odid
      - g.column name: Card.human_attribute_name(:flags),
        class: 'flags numeric', attribute: 'flags' do |card|
        - card.flags
      - g.column name: Card.human_attribute_name(:data),
        class: 'data', attribute: 'data' do |card|
        - card.data
      - g.column do |card|
        - if can? :show, card
          - link_to t('show'), card, class: 'show'
      - g.column do |card|
        - if can? :edit, card
          - link_to t('edit'), edit_card_path(card), class: 'edit'
      - g.column do |card|
        - if can? :destroy, card
          - link_to t('destroy'), card,
            data: {confirm: t('.confirm', default: 'Are you sure?')},
            method: :delete, class: 'destroy'
  -else
    %table
      %thead
        %tr
          %th= Card.human_attribute_name :nid
          %th= Card.human_attribute_name :did
          %th= Card.human_attribute_name :ord
          %th= Card.human_attribute_name :mod
          %th= Card.human_attribute_name :usn
          %th= Card.human_attribute_name :type
          %th= Card.human_attribute_name :queue
          %th= Card.human_attribute_name :due
          %th= Card.human_attribute_name :ivl
          %th= Card.human_attribute_name :factor
          %th= Card.human_attribute_name :reps
          %th= Card.human_attribute_name :lapses
          %th= Card.human_attribute_name :left
          %th= Card.human_attribute_name :odue
          %th= Card.human_attribute_name :odid
          %th= Card.human_attribute_name :flags
          %th= Card.human_attribute_name :data
          %th{colspan: 3}= t 'actions'

      %tbody
        - @cards.each do |card|
          %tr{class: cycle(:odd, :even)}
            %td.nid= card.nid
            %td.did= card.did
            %td.ord= card.ord
            %td.mod= card.mod
            %td.usn= card.usn
            %td.type= card.type
            %td.queue= card.queue
            %td.due= card.due
            %td.ivl= card.ivl
            %td.factor= card.factor
            %td.reps= card.reps
            %td.lapses= card.lapses
            %td.left= card.left
            %td.odue= card.odue
            %td.odid= card.odid
            %td.flags= card.flags
            %td.data= card.data
            %td.action
              - if can? :show, card
                = link_to t('show'), card, class: 'show'
            %td.action
              - if can? :edit, card
                = link_to t('edit'), edit_card_path(card), class: 'edit'
            %td.action
              - if can? :destroy, card
                = link_to t('destroy'), card,
                  data: {confirm: t('.confirm', default: 'Are you sure?')},
                  method: :delete, class: 'destroy'
- else
  .empty
    = t '.empty'

app/views/cards/new.html.haml
- title t('.title')

- if can? :index, Card
  %p.nav= link_to t('back'), cards_path, class: 'index'

= render 'form', card: @card

app/views/cards/show.html.haml
- title t('.title')

%p.nav
  - if can? :index, Card
    = link_to t('back'), cards_path, class: 'index'
  - if can? :edit, @card
    = link_to t('edit'), edit_card_path(@card), class: 'edit'

%dl
  %dt= Card.human_attribute_name :nid
  %dd.nid= @card.nid
  %dt= Card.human_attribute_name :did
  %dd.did= @card.did
  %dt= Card.human_attribute_name :ord
  %dd.ord= @card.ord
  %dt= Card.human_attribute_name :mod
  %dd.mod= @card.mod
  %dt= Card.human_attribute_name :usn
  %dd.usn= @card.usn
  %dt= Card.human_attribute_name :type
  %dd.type= @card.type
  %dt= Card.human_attribute_name :queue
  %dd.queue= @card.queue
  %dt= Card.human_attribute_name :due
  %dd.due= @card.due
  %dt= Card.human_attribute_name :ivl
  %dd.ivl= @card.ivl
  %dt= Card.human_attribute_name :factor
  %dd.factor= @card.factor
  %dt= Card.human_attribute_name :reps
  %dd.reps= @card.reps
  %dt= Card.human_attribute_name :lapses
  %dd.lapses= @card.lapses
  %dt= Card.human_attribute_name :left
  %dd.left= @card.left
  %dt= Card.human_attribute_name :odue
  %dd.odue= @card.odue
  %dt= Card.human_attribute_name :odid
  %dd.odid= @card.odid
  %dt= Card.human_attribute_name :flags
  %dd.flags= @card.flags
  %dt= Card.human_attribute_name :data
  %dd.data= @card.data