config/routes.rb
Rails.application.routes.draw do
  resources :cards
  resources :notes
  resources :collections do
    resources :decks
  end

  root 'collections#index'

  # scope '(:locale)',
  #     locale: Regexp.new(I18n.available_locales.map(&:to_s).join('|')) do

  
    #root 'users#index'
  # end
end

app/helpers/layout_helper.rb
# These helper methods can be called in your template to set variables to be used in the layout
# This module should be included in all views globally,
# to do so you may need to add this line to your ApplicationController
#   helper :layout
module LayoutHelper
  def title(page_title, show_title = true)
    content_for(:title) { page_title.to_s }
    @show_title = show_title
  end

  def show_title?
    @show_title
  end

  def stylesheet(*args)
    content_for(:head) { stylesheet_link_tag(*args) }
  end

  def javascript(*args)
    content_for(:head) { javascript_include_tag(*args) }
  end
end

app/views/layouts/_main_menu.html.haml
- show = {}
- show[:collections] = can?(:index, Collection)
- show[:decks]       = can?(:index, Deck)
- show[:notes]       = can?(:index, Note)
- show[:cards]       = can?(:index, Card)

%nav#main_menu
  - if show.values.find {|v| v}
    %ul.main_menu
      - if show[:collections]
        - active = controller_name == 'collections' ? 'active' : ''
        %li{:class => active}
          = link_to t('.collections'), collections_path, :class => 'collections'
      - if show[:decks]
        - active = controller_name == 'decks' ? 'active' : ''
        %li{:class => active}
          = link_to t('.decks'), collection_decks_path(collection_id: 1), :class => 'decks'
      - if show[:notes]
        - active = controller_name == 'notes' ? 'active' : ''
        %li{:class => active}
          = link_to t('.notes'), notes_path, :class => 'notes'
      - if show[:cards]
        - active = controller_name == 'cards' ? 'active' : ''
        %li{:class => active}
          = link_to t('.cards'), cards_path, :class => 'cards'

app/views/layouts/application.html.haml
!!! 5
%html

  %head
    %title
      - title = yield(:title)
      = title.present? ? title : "Untitled"
      |
      = t :application_name, default: "Data Set Automation"
    %meta{"http-equiv"=>"Content-Type", :content=>"text/html; charset=utf-8"}/
    = favicon_link_tag @favicon || 'application.ico'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Miceportal.com'}"}
    = stylesheet_link_tag 'https://fonts.googleapis.com/css?family=Roboto+Condensed', media: 'all', 'data-turbolinks-track' => true
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
    /[if lt IE 9]
      %script{src: "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"}
      %script{src: "https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"}

  %body{:lang => I18n.locale,
    :class => [controller.controller_name, controller.action_name, yield(:body_class)]}
    %header
      - if defined? root_path
        = link_to root_path, class: 'image_link' do
          = image_tag 'logo.png'
      - else
        = image_tag 'logo.png'
      #user_nav
        #locale_select
          - if I18n.available_locales.size > 1
            - I18n.available_locales.each do |lang|
              - if lang == I18n.locale
                .language.current
                  = lang.to_s.upcase
              - elsif request.get?
                - locale = I18n.locale.to_s
                - lang = lang.to_s
                - path = request.fullpath
                - path = path.index(locale) == 1 ? path.sub(locale, lang) : "/#{lang}#{path}"
                .language.other_language
                  = link_to lang.to_s.upcase, path
              - else
                .language.other_language
                  = lang.to_s.upcase

    #container
      -#= render "layouts/admin_menu"
      = render "layouts/main_menu"

      #content
        - flash.each do |name, msg|
          = content_tag :div, msg.html_safe, :id => "flash_#{name}"

        - if respond_to?(:show_title?) and show_title?
          %h1
            = yield(:title)

        #view
          = yield